matrix:
  include:
    language: python
    python: 3.6
    install: pip install -r requirements.txt
    script: coverage run py_src/test.py
    after_success: codecov

    language:
      - node_js
    install:
      - npm install -g codecov
    script:
      - npm run problem001
      - npm run test
    after_success: codecov

notifications:
  email:
    - d.schuette@online.de
