/*
 * Project Euler Problem 2 Solution
 *
 * Problem statement:
 * Each new term in the Fibonacci sequence is generated by adding
 * the previous two terms. By starting with 1 and 2, the first 10
 * terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values
 * do not exceed four million, find the sum of the even-valued terms.
 *
 * Solution description:
 * Brute-force
 *
 * Author: Daniel Schuette
 * Date: 2019/02/17
 * License: MIT (see ../LICENSE.md)
 */
"use strict";
const { performance } = require("perf_hooks");
const { timeIt } = require("./solver001.js");
const { fibonacciArr, sumOverArrayEven } = require("./solver002.js");

// calculate solution and record the elapsed time
const start = performance.now();
const fibonacciArray = fibonacciArr(4000000);
const result = sumOverArrayEven(fibonacciArray);
const end = performance.now();

// log results
console.log(`elapsed: ${timeIt(start, end)}`);
console.log(`result: ${result}`);
