/*
 * Project Euler Problem 2 Solution
 *
 * Problem statement:
 * Each new term in the Fibonacci sequence is generated by adding
 * the previous two terms. By starting with 1 and 2, the first 10
 * terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values
 * do not exceed four million, find the sum of the even-valued terms.
 *
 * Solution description:
 * Brute-force
 *
 * Author: Daniel Schuette
 * Date: 2019/02/17
 * License: MIT (see ../LICENSE.md)
 */
"use strict";
const { performance } = require("perf_hooks");
const solver = require("./solver002.js");
