// Problem 2:
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//
// problem 2 solver is implemented in solver2.go with a unit test in solver_test2.go
// run this program to return the solution of the problem with example data
package main

import (
	"fmt"
	"log"

	"github.com/DanielSchuette/geulerproject"
)

func main() {
	res, err := geulerproject.EvenFibs(4e6)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(res)
}
