/* Project Euler Problem 2 Solution: */

/* Problem statement:
Each new term in the Fibonacci sequence
is generated by adding the previous two
terms. By starting with 1 and 2, the
first 10 terms will be: 1, 1, 2, 3, 5, 8, 13,
21, 34, 55, ...
By considering the terms in the Fibonacci
sequence whose values do not exceed four
million, find the sum of the even-valued
terms. */

/* Solution description:
Brute force approach, using only the fact that
only every third Fibonacci number is even (which
follows by the recursive definition and the
fact that the sum of an even and an odd number is
odd, while the sum of two even or two odd numbers
is even.
*/


/* Author: Philipp Schuette */
/* Date: 2019/02/19 */
/* License: MIT (see ../LICENSE.md) */

#include <stdio.h>

#define TARGET 4000000


int main() {
    int sum = 0;
    int i = 1, j = 1, k = 2;
    int even = 0;

    while (k <= TARGET) {
        if (even == 0) sum = sum + k;
        even = (even + 1) % 3;
        i = j;
        j = k;
        k = i + j;
    }
    printf("Solution: %d\n", sum);
}

